-- MySQL Script generated by MySQL Workbench
-- Thu Oct 14 20:50:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema admision
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema admision
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admision` DEFAULT CHARACTER SET utf8 ;
USE `admision` ;

-- -----------------------------------------------------
-- Table `admision`.`colegio_procedencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admision`.`colegio_procedencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admision`.`tipo_examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admision`.`tipo_examen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admision`.`modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admision`.`modalidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admision`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admision`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admision`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admision`.`carrera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admision`.`ficha_postulante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admision`.`ficha_postulante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `dni` VARCHAR(20) NULL,
  `direccion` VARCHAR(255) NULL,
  `celular` VARCHAR(20) NULL,
  `correo` VARCHAR(100) NULL,
  `modalidad_id` INT NOT NULL,
  `colegio_procedencia_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  `carrera_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_ficha_postulante_modalidad`
    FOREIGN KEY (`modalidad_id`)
    REFERENCES `admision`.`modalidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_postulante_colegio_procedencia1`
    FOREIGN KEY (`colegio_procedencia_id`)
    REFERENCES `admision`.`colegio_procedencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_postulante_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `admision`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_postulante_carrera1`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `admision`.`carrera` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admision`.`examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admision`.`examen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `puntaje` INT NULL,
  `puesto` INT NULL,
  `ficha_postulante_id` INT NOT NULL,
  `tipo_examen_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_examen_ficha_postulante1`
    FOREIGN KEY (`ficha_postulante_id`)
    REFERENCES `admision`.`ficha_postulante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_examen_tipo_examen1`
    FOREIGN KEY (`tipo_examen_id`)
    REFERENCES `admision`.`tipo_examen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
