# Generated by Django 3.2.8 on 2021-10-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='negocios'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos'),
        ),
    ]
