# Generated by Django 3.2.8 on 2021-10-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20211016_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(default='', max_length=50),
        ),
    ]
