# Generated by Django 3.2.9 on 2021-11-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pedidodetalle', to='api.pedido'),
        ),
    ]
