# Generated by Django 3.2.9 on 2021-11-05 02:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo_nom', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_nom', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('empleado_nom', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('mesa_id', models.AutoField(primary_key=True, serialize=False)),
                ('mesa_nro', models.CharField(max_length=3)),
                ('mesa_cap', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_fech', models.DateTimeField(blank=True, null=True)),
                ('pedido_nro', models.CharField(blank=True, max_length=200, null=True)),
                ('pedido_est', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoPlato',
            fields=[
                ('pedido_plato_id', models.AutoField(primary_key=True, serialize=False)),
                ('pedido_plato_can', models.IntegerField()),
                ('pedido_plato_pre', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_pedido_plato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('plato_id', models.AutoField(primary_key=True, serialize=False)),
                ('plato_nom', models.CharField(max_length=200)),
                ('plato_img', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('plato_pre', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_plato',
                'managed': False,
            },
        ),
    ]
