-- MySQL Script generated by MySQL Workbench
-- Fri Oct 29 21:11:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistemapos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemapos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemapos` DEFAULT CHARACTER SET utf8 ;
USE `sistemapos` ;

-- -----------------------------------------------------
-- Table `sistemapos`.`tbl_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemapos`.`tbl_categoria` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `categoria_nom` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemapos`.`tbl_plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemapos`.`tbl_plato` (
  `plato_id` INT NOT NULL AUTO_INCREMENT,
  `plato_nom` VARCHAR(200) NOT NULL,
  `plato_img` VARCHAR(200) NULL,
  `plato_pre` DOUBLE NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`plato_id`),
  CONSTRAINT `fk_tbl_plato_tbl_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `sistemapos`.`tbl_categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemapos`.`tbl_mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemapos`.`tbl_mesa` (
  `mesa_id` INT NOT NULL,
  `mesa_nro` VARCHAR(3) NOT NULL,
  `mesa_cap` INT NULL DEFAULT 1 COMMENT 'capacidad de la mesa',
  PRIMARY KEY (`mesa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemapos`.`tbl_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemapos`.`tbl_cargo` (
  `cargo_id` INT NOT NULL,
  `cargo_nom` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`cargo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemapos`.`tbl_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemapos`.`tbl_empleado` (
  `empleado_id` INT NOT NULL AUTO_INCREMENT,
  `empleado_nom` VARCHAR(200) NOT NULL,
  `cargo_id` INT NOT NULL,
  PRIMARY KEY (`empleado_id`),
  CONSTRAINT `fk_tbl_empleado_tbl_cargo1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `sistemapos`.`tbl_cargo` (`cargo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemapos`.`tbl_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemapos`.`tbl_pedido` (
  `pedido_id` INT NOT NULL,
  `pedido_fech` DATETIME NULL,
  `pedido_nro` VARCHAR(200) NULL,
  `pedido_est` VARCHAR(100) NULL,
  `mesa_id` INT NOT NULL,
  `empleado_id` INT NOT NULL,
  PRIMARY KEY (`pedido_id`),
  CONSTRAINT `fk_tbl_pedido_tbl_mesa1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `sistemapos`.`tbl_mesa` (`mesa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `sistemapos`.`tbl_empleado` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemapos`.`tbl_pedido_plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemapos`.`tbl_pedido_plato` (
  `pedido_plato_id` INT NOT NULL AUTO_INCREMENT,
  `pedido_plato_can` INT NOT NULL,
  `pedido_plato_pre` DOUBLE NULL,
  `pedido_plato_pedido_id` INT NOT NULL,
  `pedido_plato_plato_id` INT NOT NULL,
  PRIMARY KEY (`pedido_plato_id`),
  CONSTRAINT `fk_tbl_pedido_plato_tbl_pedido1`
    FOREIGN KEY (`pedido_plato_pedido_id`)
    REFERENCES `sistemapos`.`tbl_pedido` (`pedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_plato_tbl_plato1`
    FOREIGN KEY (`pedido_plato_plato_id`)
    REFERENCES `sistemapos`.`tbl_plato` (`plato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
